CattleEnd.Web/CattleEnd.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CattleEnd.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

CattleEnd.Web/CattleEnd.Web/Controllers/SchedulesController.cs
using System.Web.Mvc;
using CattleEnd.ServiceLayer.Services;

namespace CattleEnd.Web.Controllers
{
    public class SchedulesController : Controller
    {
        private WebService webService = new WebService();

        public ActionResult Index()
        {
            var schedules = webService.GetAllSchedules();
            return View(schedules);
        }

        public ActionResult Clear()
        {
            return View();
        }

        [HttpPost, ActionName("Clear")]
        [ValidateAntiForgeryToken]
        public ActionResult ClearConfirmed()
        {
            var isCleared = webService.ClearSchedule();
            if (isCleared)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Clear");
        }
    }
}

CattleEnd.Web/CattleEnd.Web/Controllers/WarriorsController.cs
using CattleEnd.ServiceLayer.Services;
using CattleEnd.SharedModels.Models;
using System.Web.Mvc;

namespace CattleEnd.Web.Controllers
{
    public class WarriorsController : Controller
    {
        private WebService webService = new WebService();

        public ActionResult Index()
        {
            var warriors = webService.GetAllWarriors();
            return View(warriors);
        }

        public ActionResult Create()
        {
            var species = webService.GetWarriorSpecies();
            ViewBag.Species = species;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Warrior warrior)
        {
            if (ModelState.IsValid)
            {
                var isProcessed = webService.CreateWarrior(warrior);
                if (isProcessed)
                {
                    return RedirectToAction("Index");
                }
            }
            var species = webService.GetWarriorSpecies();
            ViewBag.Species = species;
            return View(warrior);
        }

        public ActionResult Assign(int id)
        {
            var warrior = webService.GetWarriorById(id);
            if (warrior == null)
            {
                return HttpNotFound();
            }
            return View(warrior);
        }

        [HttpPost, ActionName("Assign")]
        [ValidateAntiForgeryToken]
        public ActionResult AssignConfirmed(int id)
        {
            var isAssigned = webService.AssignAdditionalDay(id);
            if (isAssigned)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Assign", id);
        }

        public ActionResult Delete(int id)
        {
            var warrior = webService.GetWarriorById(id);
            if (warrior == null)
            {
                return HttpNotFound();
            }
            return View(warrior);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var isDeleted = webService.DeleteWarrior(id);
            if (isDeleted)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Delete", id);
        }
    }
}

CattleEnd.Web/CattleEnd.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="row">
    <div class="col-md-3 col-md-offset-2">
        <img src=@Url.Content("~/Content/img/legolas.jpg") id="profile-image" width="100%" height="100%" alt="legolas">
    </div>
    <div class="col-md-5 profile">
        <p>Welcome to Cattle End patrol scheduler!</p>
        <p>It's all about fine crafted wizard machine that is able to manage warriors and calculate their guard days.</p>
        <p>You can take a look around and visit our WARRIORS page or hit directly SCHEDULED DUTIES to see who is in charge in the evening.</p>
        <p>Cheerio!</p>
    </div>
</div>

CattleEnd.Web/CattleEnd.Web/Views/Schedules/Clear.cshtml
@{
    ViewBag.Title = "Clear schedule";
}

<h2>Are you sure you want to clear the schedule?</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Clear" class="btn btn-lg btn-success" /> |
        @Html.ActionLink("Back to list of scheduled duties", "Index")
    </div>
}

CattleEnd.Web/CattleEnd.Web/Views/Schedules/Index.cshtml
@model IEnumerable<CattleEnd.SharedModels.Models.Schedule>

@{
    ViewBag.Title = "List of scheduled duties";
}

<h2>List of scheduled duties</h2>

<p>
    @Html.ActionLink("Clear schedule", "Clear")
</p>
<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Guard date
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Warrior.Name)
        </td>
        <td>
            @item.GuardDate.ToString("dd.MM.yyyy")
        </td>
    </tr>
}

</table>

CattleEnd.Web/CattleEnd.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cattle End patrol scheduler</title>
    <link href="~/Content/css/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/style.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cattle End patrol scheduler", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Warriors", "Index", "Warriors")</li>
                    <li>@Html.ActionLink("Scheduled duties", "Index", "Schedules")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

CattleEnd.Web/CattleEnd.Web/Views/Warriors/Assign.cshtml
@model CattleEnd.SharedModels.Models.Warrior

@{
    ViewBag.Title = "Assign guard day";
}

<h2>Are you sure you want to assign additional guard day for this warrior?</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Name
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Species
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Species.Name)
        </dd>
        <dt>
            Email
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Assign" class="btn btn-lg btn-success" /> |
            @Html.ActionLink("Back to list of warriors", "Index")
        </div>
    }
</div>

CattleEnd.Web/CattleEnd.Web/Views/Warriors/Create.cshtml
@model CattleEnd.SharedModels.Models.Warrior

@{
    ViewBag.Title = "Create warrior";
}

<h2>Create warrior</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SpeciesId, "Species", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SpeciesId", new SelectList(ViewBag.Species, "Id", "Name"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SpeciesId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-lg btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to list of warriors", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

CattleEnd.Web/CattleEnd.Web/Views/Warriors/Delete.cshtml
@model CattleEnd.SharedModels.Models.Warrior

@{
    ViewBag.Title = "Delete warrior";
}

<h2>Are you sure you want to delete this warrior?</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Name
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Species
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Species.Name)
        </dd>
        <dt>
            Email
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-lg btn-success" /> |
            @Html.ActionLink("Back to list of warriors", "Index")
        </div>
    }
</div>

CattleEnd.Web/CattleEnd.Web/Views/Warriors/Index.cshtml
@model IEnumerable<CattleEnd.SharedModels.Models.Warrior>

@{
    ViewBag.Title = "List of warriors";
}

<h2>List of warriors</h2>

<p>
    @Html.ActionLink("Create new", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Species
        </th>
        <th>
            Email
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Species.Name)
        </td>
        <td>
            @item.Email
        </td>
        <td>
            @Html.ActionLink("Assign additional guard day", "Assign", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}
</table>